// // export const metadata = {
// //   title: 'Next.js',
// //   description: 'Generated by Next.js',
// // }

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body>{children}</body>
// //     </html>
// //   )
// // }







// import localFont from "next/font/local";
// import "./globals.css";
// import Navbar from "./components/navbar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons:{
//     icon: "./favicon.ico"
//   }

// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <link rel="icon" href="/favicon.ico" sizes="any" />
//         <Navbar />

//         {children}
//       </body>
//     </html>
//   );
// }




export const metadata = {
  title: 'My Website',
  description: 'This is my Next.js 14 website with a custom layout',
};

import './globals.css'; // Sizning umumiy CSS fayllaringiz shu yerda
import Header from './components/Header';
import Footer from './components/Footer';

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">
          {children} {/* Sahifa kontenti shu yerda o'zgaradi */}
        </main>
        <Footer />
      </body>
    </html>
  );
}
